import React, { useState, useEffect } from 'react';
import { Card, Row, Col, Button, Table, Tag, DatePicker, Select, Typography, message, Space, Statistic } from 'antd';
import { FilePdfOutlined, DownloadOutlined, ReloadOutlined, BarChartOutlined, DeleteOutlined } from '@ant-design/icons';
import api, { getMediaUrl } from '../api/client';
import dayjs from 'dayjs';
import { Popconfirm } from 'antd';

const { Title, Text } = Typography;
const { Option } = Select;

const Reports = () => {
    const [loading, setLoading] = useState(false);
    const [recentReports, setRecentReports] = useState([]);
    const [reportType, setReportType] = useState('Attendance Report');
    const [dateRange, setDateRange] = useState('This Month');
    const [students, setStudents] = useState([]);
    const [selectedStudent, setSelectedStudent] = useState(null);
    const [generating, setGenerating] = useState(false);

    const fetchInitialData = async () => {
        setLoading(true);
        try {
            const [reportsRes, studentsRes] = await Promise.all([
                api.get('/reports/recent'),
                api.get('/students')
            ]);
            setRecentReports(reportsRes.data);
            setStudents(studentsRes.data);
        } catch (_) {
            message.error('Failed to fetch initial data');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchInitialData();
    }, []);

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            await api.post('/reports/generate', {
                type: reportType,
                dateRange,
                studentId: selectedStudent || null
            });
            message.success('Report generated successfully');
            fetchInitialData();
        } catch (error) {
            message.error(error.response?.data?.message || 'Failed to generate report');
        } finally {
            setGenerating(false);
        }
    };

    const handleDownload = async (id, filePath) => {
        if (filePath) {
            window.open(getMediaUrl(filePath), '_blank');
        } else {
            try {
                const response = await api.get(`/reports/download/${id}`);
                if (response.data.downloadUrl) {
                    window.open(getMediaUrl(response.data.downloadUrl), '_blank');
                }
            } catch (_) {
                message.error('Failed to download report');
            }
        }
    };

    const handleDelete = async (id) => {
        try {
            await api.delete(`/reports/${id}`);
            message.success('Report deleted successfully');
            fetchInitialData();
        } catch (_) {
            message.error('Failed to delete report');
        }
    };

    const columns = [
        {
            title: 'Report Type',
            dataIndex: 'reportType',
            key: 'reportType',
            render: (text) => <Text strong style={{ color: '#2D3436' }}>{text}</Text>,
        },
        {
            title: 'Scope',
            dataIndex: 'dateRange',
            key: 'dateRange',
            render: (text) => <Tag color="purple">{text}</Tag>
        },
        {
            title: 'Generated By',
            dataIndex: ['user', 'fullName'],
            key: 'generatedBy',
            render: (text) => <Text type="secondary" style={{ fontSize: 12 }}>{text}</Text>
        },
        {
            title: 'Date Generated',
            dataIndex: 'createdAt',
            key: 'createdAt',
            render: (date) => <Text type="secondary" style={{ fontSize: 12 }}>{dayjs(date).format('MMM D, HH:mm')}</Text>,
        },
        {
            title: 'Action',
            key: 'action',
            render: (_, record) => (
                <Space>
                    <Button
                        type="primary"
                        ghost
                        size="small"
                        icon={<DownloadOutlined />}
                        onClick={() => handleDownload(record.id, record.filePath)}
                        style={{ borderColor: '#7B57E4', color: '#7B57E4' }}
                    >
                        PDF
                    </Button>
                    <Popconfirm
                        title="Delete Report"
                        description="Are you sure you want to delete this report and its PDF file?"
                        onConfirm={() => handleDelete(record.id)}
                        okText="Yes"
                        cancelText="No"
                        okButtonProps={{ danger: true }}
                    >
                        <Button
                            type="text"
                            danger
                            size="small"
                            icon={<DeleteOutlined />}
                        />
                    </Popconfirm>
                </Space>
            ),
        },
    ];

    return (
        <div style={{ padding: 24 }}>
            <div style={{ marginBottom: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <Title level={2} style={{ margin: 0, color: '#2D3436' }}>Reports</Title>
                    <Text type="secondary">Generate and manage official system reports and student assessments.</Text>
                </div>
                <Button icon={<ReloadOutlined />} onClick={fetchInitialData}>Refresh History</Button>
            </div>

            <Row gutter={[24, 24]}>
                <Col xs={24} lg={9}>
                    <Card
                        title={<span style={{ color: '#7B57E4' }}>Report Configuration</span>}
                        bordered={false}
                        style={{ height: '100%', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}
                    >
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                            <div>
                                <Text strong style={{ display: 'block', marginBottom: 8, color: '#636E72' }}>Report Category</Text>
                                <Select
                                    value={reportType}
                                    onChange={setReportType}
                                    style={{ width: '100%' }}
                                    size="large"
                                >
                                    <Option value="Attendance Report">Attendance & Engagement (Classroom-wise)</Option>
                                    <Option value="Student Progress Report">Skill Development & Proficiency</Option>
                                </Select>
                            </div>

                            <div>
                                <Text strong style={{ display: 'block', marginBottom: 8, color: '#636E72' }}>Timeframe</Text>
                                <Select
                                    value={dateRange}
                                    onChange={setDateRange}
                                    style={{ width: '100%' }}
                                    size="large"
                                >
                                    <Option value="This Month">Current Month Cycle</Option>
                                    <Option value="Last Month">Previous Month Cycle</Option>
                                    <Option value="Year to Date">Year to Date (YTD)</Option>
                                </Select>
                            </div>

                            {reportType === 'Student Progress Report' && (
                                <div style={{ padding: '0 0 15px 0' }}>
                                    <Text strong style={{ display: 'block', marginBottom: 8, color: '#636E72' }}>Specific Student (Optional)</Text>
                                    <Select
                                        showSearch
                                        allowClear
                                        placeholder="Select to generate Individual Profile"
                                        optionFilterProp="children"
                                        onChange={setSelectedStudent}
                                        style={{ width: '100%' }}
                                        size="large"
                                    >
                                        {students.map(s => (
                                            <Option key={s.id} value={s.id}>{s.fullName} ({s.studentUniqueId})</Option>
                                        ))}
                                    </Select>
                                    <Text type="secondary" style={{ fontSize: 11, marginTop: 6, display: 'block' }}>
                                        * Leave blank to generate an <strong>Aggregate Class Proficiency Analysis</strong>.
                                    </Text>
                                </div>
                            )}

                            <Button
                                type="primary"
                                icon={<BarChartOutlined />}
                                loading={generating}
                                onClick={handleGenerate}
                                size="large"
                                style={{
                                    marginTop: 10,
                                    height: 48,
                                    background: 'linear-gradient(135deg, #7B57E4 0%, #6C5CE7 100%)',
                                    border: 'none',
                                    borderRadius: 8,
                                    fontWeight: 600,
                                    boxShadow: '0 4px 10px rgba(108, 92, 231, 0.3)'
                                }}
                                block
                            >
                                Generate Analytics Booklet
                            </Button>
                        </div>
                    </Card>
                </Col>

                <Col xs={24} lg={15}>
                    <Card title="Recent Reports" bordered={false} style={{ height: '100%', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}>
                        <Table
                            dataSource={recentReports}
                            columns={columns}
                            rowKey="id"
                            loading={loading}
                            pagination={{ pageSize: 5 }}
                        />
                    </Card>
                </Col>
            </Row>
        </div>
    );
};

export default Reports;
