import React, { useState, useEffect } from 'react';
import { Card, Row, Col, Button, Table, Tag, DatePicker, Select, Typography, message, Space, Statistic } from 'antd';
import { FilePdfOutlined, DownloadOutlined, ReloadOutlined, BarChartOutlined } from '@ant-design/icons';
import mockApi from '../api/client';
import dayjs from 'dayjs';

const { Title, Text } = Typography;
const { Option } = Select;

const Reports = () => {
    const [loading, setLoading] = useState(false);
    const [recentReports, setRecentReports] = useState([]);
    const [reportType, setReportType] = useState('Attendance Report');
    const [dateRange, setDateRange] = useState('This Month');
    const [generating, setGenerating] = useState(false);

    const fetchRecentReports = async () => {
        setLoading(true);
        try {
            const response = await mockApi.get('/reports/recent');
            setRecentReports(response.data);
        } catch (error) {
            message.error('Failed to fetch recent reports');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchRecentReports();
    }, []);

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            const response = await mockApi.post('/reports/generate', {
                type: reportType,
                dateRange
            });
            message.success('Report generated successfully');
            if (response.data.details) {
                // Show details notification or update UI
                const details = Object.entries(response.data.details).map(([k, v]) => `${k}: ${v}`).join(', ');
                message.info(`Report Summary: ${details}`);
            }
            fetchRecentReports();
        } catch (error) {
            message.error(error.errorMessage || 'Failed to generate report');
        } finally {
            setGenerating(false);
        }
    };

    const handleDownload = async (id) => {
        try {
            const response = await mockApi.get(`/reports/download/${id}`);
            // Mock download
            message.success(`Downloading ${response.data.fileName}...`);
            // In real app, window.open(response.data.downloadUrl);
        } catch (error) {
            message.error('Failed to download report');
        }
    };

    const columns = [
        {
            title: 'Report Type',
            dataIndex: 'reportType',
            key: 'reportType',
            render: (text) => <Text strong>{text}</Text>,
        },
        {
            title: 'Date Range',
            dataIndex: 'dateRange',
            key: 'dateRange',
        },
        {
            title: 'Generated By',
            dataIndex: ['user', 'fullName'],
            key: 'generatedBy',
        },
        {
            title: 'Date Generated',
            dataIndex: 'createdAt',
            key: 'createdAt',
            render: (date) => dayjs(date).format('YYYY-MM-DD HH:mm'),
        },
        {
            title: 'Action',
            key: 'action',
            render: (_, record) => (
                <Button
                    type="link"
                    icon={<DownloadOutlined />}
                    onClick={() => handleDownload(record.id)}
                    style={{ color: '#7B57E4' }}
                >
                    Download
                </Button>
            ),
        },
    ];

    return (
        <div style={{ padding: 24 }}>
            <div style={{ marginBottom: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <Title level={2} style={{ margin: 0 }}>Reports</Title>
                    <Text type="secondary">Generate and view system reports</Text>
                </div>
                <Button icon={<ReloadOutlined />} onClick={fetchRecentReports} style={{ color: '#7B57E4', borderColor: '#7B57E4' }}>Refresh</Button>
            </div>

            <Row gutter={[24, 24]}>
                <Col xs={24} lg={8}>
                    <Card title="Generate New Report" bordered={false} style={{ height: '100%' }}>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                            <div>
                                <Text strong style={{ display: 'block', marginBottom: 8 }}>Report Type</Text>
                                <Select
                                    value={reportType}
                                    onChange={setReportType}
                                    style={{ width: '100%' }}
                                >
                                    <Option value="Attendance Report">Attendance Report</Option>
                                    <Option value="Classroom Report">Classroom Report</Option>
                                    <Option value="Financial Report">Financial Report</Option>
                                </Select>
                            </div>

                            <div>
                                <Text strong style={{ display: 'block', marginBottom: 8 }}>Date Range</Text>
                                <Select
                                    value={dateRange}
                                    onChange={setDateRange}
                                    style={{ width: '100%' }}
                                >
                                    <Option value="This Month">This Month</Option>
                                    <Option value="Last Month">Last Month</Option>
                                    <Option value="Year to Date">Year to Date</Option>
                                </Select>
                            </div>

                            <Button
                                type="primary"
                                icon={<BarChartOutlined />}
                                loading={generating}
                                onClick={handleGenerate}
                                style={{ marginTop: 16, height: 40, background: '#7B57E4', borderColor: '#7B57E4', borderRadius: 8 }}
                                block
                            >
                                Generate Report
                            </Button>
                        </div>
                    </Card>
                </Col>

                <Col xs={24} lg={16}>
                    <Card title="Recent Reports" bordered={false} style={{ height: '100%' }}>
                        <Table
                            dataSource={recentReports}
                            columns={columns}
                            rowKey="id"
                            loading={loading}
                            pagination={{ pageSize: 5 }}
                        />
                    </Card>
                </Col>
            </Row>
        </div>
    );
};

export default Reports;
