import React, { useState, useEffect } from 'react';
import { Card, Row, Col, Button, Table, Tag, DatePicker, Select, Typography, message, Space, Statistic } from 'antd';
import { FilePdfOutlined, DownloadOutlined, ReloadOutlined, BarChartOutlined } from '@ant-design/icons';
import mockApi from '../api/client';
import dayjs from 'dayjs';

const { Title, Text } = Typography;
const { Option } = Select;

const Reports = () => {
    const [loading, setLoading] = useState(false);
    const [recentReports, setRecentReports] = useState([]);
    const [reportType, setReportType] = useState('Attendance Report');
    const [dateRange, setDateRange] = useState('This Month');
    const [students, setStudents] = useState([]);
    const [selectedStudent, setSelectedStudent] = useState(null);
    const [classrooms, setClassrooms] = useState([]);
    const [selectedClassroom, setSelectedClassroom] = useState('All');
    const [generating, setGenerating] = useState(false);

    const fetchInitialData = async () => {
        setLoading(true);
        try {
            const [reportsRes, classroomsRes, studentsRes] = await Promise.all([
                mockApi.get('/reports/recent'),
                mockApi.get('/classrooms'),
                mockApi.get('/students')
            ]);
            setRecentReports(reportsRes.data);
            setClassrooms(classroomsRes.data);
            setStudents(studentsRes.data);
        } catch (error) {
            message.error('Failed to fetch initial data');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchInitialData();
    }, []);

    const handleGenerate = async () => {
        // Aggregate mode is now supported for Progress Reports
        setGenerating(true);
        try {
            const response = await mockApi.post('/reports/generate', {
                type: reportType,
                dateRange,
                classroomId: selectedClassroom === 'All' ? null : selectedClassroom,
                studentId: selectedStudent || null // Send null if empty
            });
            message.success('Advanced report generated successfully');
            if (response.data.details) {
                // If simple summary exists, show it. Advanced reports rely on the PDF.
                if (typeof response.data.details === 'object') {
                    const details = Object.entries(response.data.details).map(([k, v]) => `${k}: ${v}`).join(', ');
                    message.info(`Snapshot: ${details}`);
                }
            }
            fetchInitialData();
        } catch (error) {
            message.error(error.errorMessage || 'Failed to generate report');
        } finally {
            setGenerating(false);
        }
    };

    const handleDownload = async (id, filePath) => {
        const BASE_URL = 'http://127.0.0.1:5000';
        if (filePath) {
            const fullPath = filePath.startsWith('http') ? filePath : `${BASE_URL}/${filePath.replace(/^\//, '')}`;
            window.open(fullPath, '_blank');
        } else {
            try {
                const response = await mockApi.get(`/reports/download/${id}`);
                if (response.data.downloadUrl) {
                    const dlUrl = response.data.downloadUrl;
                    const fullDlPath = dlUrl.startsWith('http') ? dlUrl : `${BASE_URL}/${dlUrl.replace(/^\//, '')}`;
                    window.open(fullDlPath, '_blank');
                }
            } catch (error) {
                message.error('Failed to download report');
            }
        }
    };

    const columns = [
        {
            title: 'Report Type',
            dataIndex: 'reportType',
            key: 'reportType',
            render: (text) => <Text strong style={{ color: '#2D3436' }}>{text}</Text>,
        },
        {
            title: 'Scope',
            dataIndex: 'dateRange',
            key: 'dateRange',
            render: (text) => <Tag color="purple">{text}</Tag>
        },
        {
            title: 'Generated By',
            dataIndex: ['user', 'fullName'],
            key: 'generatedBy',
            render: (text) => <Text type="secondary" style={{ fontSize: 12 }}>{text}</Text>
        },
        {
            title: 'Date Generated',
            dataIndex: 'createdAt',
            key: 'createdAt',
            render: (date) => <Text type="secondary" style={{ fontSize: 12 }}>{dayjs(date).format('MMM D, HH:mm')}</Text>,
        },
        {
            title: 'Action',
            key: 'action',
            render: (_, record) => (
                <Button
                    type="primary"
                    ghost
                    size="small"
                    icon={<DownloadOutlined />}
                    onClick={() => handleDownload(record.id, record.filePath)}
                    style={{ borderColor: '#7B57E4', color: '#7B57E4' }}
                >
                    PDF
                </Button>
            ),
        },
    ];

    return (
        <div style={{ padding: 24 }}>
            <div style={{ marginBottom: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <Title level={2} style={{ margin: 0, color: '#2D3436' }}>Royal Analytics</Title>
                    <Text type="secondary">Generate comprehensive, data-driven booklets for decision support.</Text>
                </div>
                <Button icon={<ReloadOutlined />} onClick={fetchInitialData}>Refresh History</Button>
            </div>

            <Row gutter={[24, 24]}>
                <Col xs={24} lg={9}>
                    <Card
                        title={<span style={{ color: '#7B57E4' }}>Report Configuration</span>}
                        bordered={false}
                        style={{ height: '100%', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}
                    >
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                            <div>
                                <Text strong style={{ display: 'block', marginBottom: 8, color: '#636E72' }}>Report Category</Text>
                                <Select
                                    value={reportType}
                                    onChange={setReportType}
                                    style={{ width: '100%' }}
                                    size="large"
                                >
                                    <Option value="Attendance Report">Attendance & Engagement (Classroom-wise)</Option>
                                    <Option value="Financial Report">Financial Health & Collection Analysis</Option>
                                    <Option value="Student Progress Report">Skill Development & Proficiency</Option>
                                </Select>
                            </div>

                            <div>
                                <Text strong style={{ display: 'block', marginBottom: 8, color: '#636E72' }}>Timeframe</Text>
                                <Select
                                    value={dateRange}
                                    onChange={setDateRange}
                                    style={{ width: '100%' }}
                                    size="large"
                                >
                                    <Option value="This Month">Current Month Cycle</Option>
                                    <Option value="Last Month">Previous Month Cycle</Option>
                                    <Option value="Year to Date">Year to Date (YTD)</Option>
                                </Select>
                            </div>

                            {reportType === 'Student Progress Report' && (
                                <div style={{ padding: '0 0 15px 0' }}>
                                    <Text strong style={{ display: 'block', marginBottom: 8, color: '#636E72' }}>Specific Student (Optional)</Text>
                                    <Select
                                        showSearch
                                        allowClear
                                        placeholder="Select to generate Individual Profile"
                                        optionFilterProp="children"
                                        onChange={setSelectedStudent}
                                        style={{ width: '100%' }}
                                        size="large"
                                    >
                                        {students.map(s => (
                                            <Option key={s.id} value={s.id}>{s.fullName} ({s.studentUniqueId})</Option>
                                        ))}
                                    </Select>
                                    <Text type="secondary" style={{ fontSize: 11, marginTop: 6, display: 'block' }}>
                                        * Leave blank to generate an <strong>Aggregate Class Proficiency Analysis</strong>.
                                    </Text>
                                </div>
                            )}

                            <Button
                                type="primary"
                                icon={<BarChartOutlined />}
                                loading={generating}
                                onClick={handleGenerate}
                                size="large"
                                style={{
                                    marginTop: 10,
                                    height: 48,
                                    background: 'linear-gradient(135deg, #7B57E4 0%, #6C5CE7 100%)',
                                    border: 'none',
                                    borderRadius: 8,
                                    fontWeight: 600,
                                    boxShadow: '0 4px 10px rgba(108, 92, 231, 0.3)'
                                }}
                                block
                            >
                                Generate Analytics Booklet
                            </Button>
                        </div>
                    </Card>
                </Col>

                <Col xs={24} lg={15}>
                    <Card title="Recent Reports" bordered={false} style={{ height: '100%', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}>
                        <Table
                            dataSource={recentReports}
                            columns={columns}
                            rowKey="id"
                            loading={loading}
                            pagination={{ pageSize: 5 }}
                        />
                    </Card>
                </Col>
            </Row>
        </div>
    );
};

export default Reports;
